# Generated by Django 4.0.4 on 2022-05-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('username', models.CharField(default='', max_length=254)),
                ('email', models.EmailField(default='', max_length=254)),
                ('email_sent', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=254)),
                ('surname', models.CharField(default='', max_length=254)),
                ('role', models.CharField(choices=[('Analyst', 'Analyst'), ('Team Manager', 'Team Manager'), ('Quality Auditor', 'Quality Auditor'), ('Senior Analyst', 'Senior Analyst'), ('', '')], default='', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
