# Generated by Django 4.0.4 on 2022-05-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_resource_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='email',
        ),
    ]
