# Generated by Django 4.0.4 on 2022-05-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_resource_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='username',
            field=models.CharField(default='', max_length=254),
        ),
    ]
