# Generated by Django 4.0.4 on 2022-05-21 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_resource_username'),
        ('scheduler', '0003_alter_addresource_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresource',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to='users.resource'),
        ),
    ]
