# Generated by Django 4.0.4 on 2022-05-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_event_user_alter_event_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='shift',
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(choices=[('Early', 'E'), ('Middle', 'M'), ('Late', 'L'), ('Holiday', 'H'), ('Bank Holiday', 'BH'), ('', '')], default='', max_length=30),
        ),
    ]
